### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [samuelmbp/dev-portfolio#2]
# Feedback

## Requirements:

1. A deployed website (using GitHub Pages)
2. A public GitHub repository for your codebase
3. Use HTML & SCSS
4. Make good use of semantic HTML elements
5. Be responsive (mobile-first) and built with accessibility in mind
6. Code is highly readable (good naming and indented correctly)

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Waiheke-Course-Resources/blob/main/student-resources/01-web/marking-scheme.md)

| Category             | Score    |
| -------------------- | -------- |
| Site Output          | 40 / 50  |
| Responsiveness       | 15 / 15  |
| Code Knowledge & Use | 15 / 20  |
| Readability          | 15 / 15  |
| Version Control      | 10 / 10  |
| Total Score          | 95 / 110 |

### Positive

- Your project is great! it has been a good exercise for you to build a website from a wireframe.
  - If you ever need a break pick a website and try and recreate it.
- Great use of media queries, try using variables for the breakpoints in your next project.

  - `@media screen and (min-width: 900px) {}` -> `@media screen and (min-width: $tablet-breakpoint) {}`

- I am glad you pushed yourself by choosing to add multiple breakpoints, with modular SCSS.

- You have extended and customized the project which is a good habit to be in.

  - Please keep this up as you complete projects and your profile use it and add them to your portfolio.

- You are demonstrating a solid understanding of the majority of topics we have covered so far, keep it up and keep on using BEM, SCSS, grid and flex.

### Constructive

- I think you have a couple of examples in your code where you would use a modifier, not a separate class

  - `<div class="projects__card hide__project">` -> `<div class="projects__card projects__card--hide">`
  - `<p class="about__description first__paragraph">` -> `<p class="about__description about__description--first">`
  - `<p class="about__description second__paragraph">` -> `<p class="about__description about__description--second">`

- Your `projects__card` could do with some refactoring as there are some inconsistencies with the application of BEM and styles.
  - I think it makes sense for it to be a block as the styles are tied to an individual card.

```html
<!-- CURRENT CODE -->
<div class="projects__card hide__project">
  <div class="image__container"></div>
  <div class="projects__card-body">
    <span class="projects__card-language">REACT</span>
    <h3 class="projects__card-subheading">PUNK API</h3>
    <p class="projects__card-description">
      There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some
      form, by injected humour, or randomised words which don't look even slightly believable.
    </p>
    <div class="card__buttons">
      <div class="card__flex">
        <a class="card__button" href="#">Code </a>
        <img src="./assets/coding.png" alt="" />
      </div>

      <div class="card__flex">
        <a class="card__button" href="#">Preview</a>
        <img width="16" height="16" src="./assets/eye-regular.svg" alt="" />
      </div>
    </div>
  </div>
</div>

<!-- COULD BE -->

<!-- MAKE PROJECT A BLOCK -->
<div class="project project--hide">
  <!-- ALL OF THE HTML ARE ITS ELEMENTS SO THEY ALL HAVE project__-->
  <div class="project__image"></div>
  <div class="project__card-body">
    <span class="project__language">REACT</span>
    <h3 class="project__sub-heading">PUNK API</h3>
    <p class="project__description">
      There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some
      form, by injected humour, or randomised words which don't look even slightly believable.
    </p>

    <div class="project__buttons">
      <div class="project__button-container">
        <a class="project__button" href="#">Code </a>
        <img class="project__icon" src="./assets/coding.png" alt="" />
      </div>
      <div class="project__button-container">
        <a class="project__button" href="#">Preview</a>
        <!-- REMOVE THE HEIGHT AND WIDTH AND DO THAT IN THE STYLES -->
        <img class="project__icon" src="./assets/eye-regular.svg" alt="" />
      </div>
    </div>
  </div>
</div>
```

- With your styles you are nesting them too deeply which can cause issues with specificity it should only ever be block -> element -> modifier.
  - At the moment you have `.projects`->`.projects__card`->`.projects__card-body`->`.card__buttons` -> `.card__button` giving this a specificity of 0,5,0
  - The code snippet below moves `.projects__card` into its own block and unnests the styles meaning that the selector for the button is just `.project`->`.project__button`.
    - The block and then the modifier.

```scss
.projects {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background-color: $light-gray;

  .projects__heading {
    text-align: center;
    margin-bottom: 45px;
    margin-top: 55px;
  }
}

.project {
  width: 290px;
  height: 550px;
  margin-top: 12px;
  margin-bottom: 55px;

  &--hide {
    display: none;
  }

  .project__image {
    height: 225px;
    background-color: $light-secondary;
    border-radius: 8px;
    object-fit: cover;
  }

  .project__card-body {
    margin-top: 24px;
  }

  .project__language {
    color: $secondary-color;
    font-size: 12px;
  }

  .project__sub-heading {
    font-size: 22px;
    margin-top: 10px;
  }

  .project__description {
    margin-top: 24px;
    color: $dark-gray;
  }

  .project__buttons {
    margin-top: 20px;
    display: flex;
    gap: 12px;
    align-items: center;
  }

  .project__button-container {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 7px;
  }

  .project__button {
    text-decoration: none;
    color: $primary-color;
    font-size: 12px;
  }

  .project__icon {
    height: 16px;
    width: 16px;
  }
}
```

---
